name: fypdashboard
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  cached_network_image: ^3.3.1
  fl_chart: ^0.67.0
  flutter:
    sdk: flutter
  flutter_charts: ^0.5.2
  flutter_launcher_icons: ^0.13.1
  flutter_svg: ^2.0.10+1
  get: ^4.6.6
  get_storage: ^2.1.1
  google_fonts: ^6.2.0
  html: ^0.15.4
  http: ^1.2.1
  http_parser: ^4.0.2
  image_picker: ^1.0.7
  intl: ^0.19.0
  mime: ^1.0.5
  sidebarx: ^0.16.3
  simple_fontellico_progress_dialog: ^0.3.0
  url_launcher: ^6.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

assets:
  - assets/images/
  - assets/icons/
  - assets/fonts/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/output-onlinepngtools.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/images/output-onlinepngtools.png"
    # background_color: "#hexcode"
    # theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/images/output-onlinepngtools.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/images/output-onlinepngtools.png"
